--
-- PostgreSQL database dump
--

\restrict 2iOOftOcdRDsRitUcd8oQ06Gnxz4RvtcN4JaBsDfbNVMORhEx575ConxR7kiwfa

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: incidents_actionlog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_actionlog (
    id bigint NOT NULL,
    action_type character varying(100) NOT NULL,
    description text NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    user_id bigint,
    appeal_id bigint
);


ALTER TABLE public.incidents_actionlog OWNER TO postgres;

--
-- Name: incidents_actionlog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_actionlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_actionlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_appeal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_appeal (
    id bigint NOT NULL,
    topic character varying(200) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    closed_at timestamp with time zone,
    applicant_id bigint NOT NULL,
    category_id bigint,
    priority_id bigint,
    status_id bigint
);


ALTER TABLE public.incidents_appeal OWNER TO postgres;

--
-- Name: incidents_appeal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_appeal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_appeal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_assignment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_assignment (
    id bigint NOT NULL,
    assigned_at timestamp with time zone NOT NULL,
    comment text NOT NULL,
    appeal_id bigint NOT NULL,
    performer_id bigint NOT NULL
);


ALTER TABLE public.incidents_assignment OWNER TO postgres;

--
-- Name: incidents_assignment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_assignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_backuplog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_backuplog (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    file_name character varying(255) NOT NULL,
    status character varying(50) NOT NULL,
    file_path character varying(500) NOT NULL,
    initiator_id bigint
);


ALTER TABLE public.incidents_backuplog OWNER TO postgres;

--
-- Name: incidents_backuplog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_backuplog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_backuplog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.incidents_category OWNER TO postgres;

--
-- Name: incidents_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_comment (
    id bigint NOT NULL,
    text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    appeal_id bigint NOT NULL,
    author_id bigint NOT NULL
);


ALTER TABLE public.incidents_comment OWNER TO postgres;

--
-- Name: incidents_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    fio character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    department_id bigint,
    role_id bigint
);


ALTER TABLE public.incidents_customuser OWNER TO postgres;

--
-- Name: incidents_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.incidents_customuser_groups OWNER TO postgres;

--
-- Name: incidents_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.incidents_customuser_user_permissions OWNER TO postgres;

--
-- Name: incidents_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_department (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    head character varying(100) NOT NULL,
    phone character varying(20) NOT NULL
);


ALTER TABLE public.incidents_department OWNER TO postgres;

--
-- Name: incidents_department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_priority; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_priority (
    id bigint NOT NULL,
    level character varying(50) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.incidents_priority OWNER TO postgres;

--
-- Name: incidents_priority_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_priority ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_priority_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_report; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_report (
    id bigint NOT NULL,
    report_type character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    appeal_count integer NOT NULL,
    file_path character varying(100) NOT NULL,
    initiator_id bigint NOT NULL
);


ALTER TABLE public.incidents_report OWNER TO postgres;

--
-- Name: incidents_report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_role (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.incidents_role OWNER TO postgres;

--
-- Name: incidents_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents_status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidents_status (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.incidents_status OWNER TO postgres;

--
-- Name: incidents_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidents_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add Категория	5	add_category
2	Can change Категория	5	change_category
3	Can delete Категория	5	delete_category
4	Can view Категория	5	view_category
5	Can add Отдел	8	add_department
6	Can change Отдел	8	change_department
7	Can delete Отдел	8	delete_department
8	Can view Отдел	8	view_department
9	Can add Приоритет	9	add_priority
10	Can change Приоритет	9	change_priority
11	Can delete Приоритет	9	delete_priority
12	Can view Приоритет	9	view_priority
13	Can add Роль	11	add_role
14	Can change Роль	11	change_role
15	Can delete Роль	11	delete_role
16	Can view Роль	11	view_role
17	Can add Статус	12	add_status
18	Can change Статус	12	change_status
19	Can delete Статус	12	delete_status
20	Can view Статус	12	view_status
21	Can add Пользователь	7	add_customuser
22	Can change Пользователь	7	change_customuser
23	Can delete Пользователь	7	delete_customuser
24	Can view Пользователь	7	view_customuser
25	Can add Обращение	2	add_appeal
26	Can change Обращение	2	change_appeal
27	Can delete Обращение	2	delete_appeal
28	Can view Обращение	2	view_appeal
29	Can add Журнал действий	1	add_actionlog
30	Can change Журнал действий	1	change_actionlog
31	Can delete Журнал действий	1	delete_actionlog
32	Can view Журнал действий	1	view_actionlog
33	Can add Назначение	3	add_assignment
34	Can change Назначение	3	change_assignment
35	Can delete Назначение	3	delete_assignment
36	Can view Назначение	3	view_assignment
37	Can add Резервная копия	4	add_backuplog
38	Can change Резервная копия	4	change_backuplog
39	Can delete Резервная копия	4	delete_backuplog
40	Can view Резервная копия	4	view_backuplog
41	Can add Комментарий (Чат)	6	add_comment
42	Can change Комментарий (Чат)	6	change_comment
43	Can delete Комментарий (Чат)	6	delete_comment
44	Can view Комментарий (Чат)	6	view_comment
45	Can add Отчет	10	add_report
46	Can change Отчет	10	change_report
47	Can delete Отчет	10	delete_report
48	Can view Отчет	10	view_report
49	Can add log entry	13	add_logentry
50	Can change log entry	13	change_logentry
51	Can delete log entry	13	delete_logentry
52	Can view log entry	13	view_logentry
53	Can add permission	15	add_permission
54	Can change permission	15	change_permission
55	Can delete permission	15	delete_permission
56	Can view permission	15	view_permission
57	Can add group	14	add_group
58	Can change group	14	change_group
59	Can delete group	14	delete_group
60	Can view group	14	view_group
61	Can add content type	16	add_contenttype
62	Can change content type	16	change_contenttype
63	Can delete content type	16	delete_contenttype
64	Can view content type	16	view_contenttype
65	Can add session	17	add_session
66	Can change session	17	change_session
67	Can delete session	17	delete_session
68	Can view session	17	view_session
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-12-22 22:56:55.595268+03	1	Отдел по борьбе	1	[{"added": {}}]	8	1
2	2025-12-22 23:01:14.299723+03	1	Admin	1	[{"added": {}}]	11	1
3	2025-12-22 23:01:39.703678+03	2	Staff	1	[{"added": {}}]	11	1
4	2025-12-22 23:01:54.855471+03	3	User	1	[{"added": {}}]	11	1
5	2025-12-22 23:06:27.834836+03	3	User	3		11	1
6	2025-12-22 23:06:27.834858+03	2	Staff	3		11	1
7	2025-12-22 23:06:27.834869+03	1	Admin	3		11	1
8	2025-12-22 23:55:06.330865+03	1	admin (Попов Владислав Александрович)	2	[{"changed": {"fields": ["\\u0424\\u0418\\u041e", "\\u0420\\u043e\\u043b\\u044c"]}}]	7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	incidents	actionlog
2	incidents	appeal
3	incidents	assignment
4	incidents	backuplog
5	incidents	category
6	incidents	comment
7	incidents	customuser
8	incidents	department
9	incidents	priority
10	incidents	report
11	incidents	role
12	incidents	status
13	admin	logentry
14	auth	group
15	auth	permission
16	contenttypes	contenttype
17	sessions	session
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-12-22 22:38:49.29939+03
2	contenttypes	0002_remove_content_type_name	2025-12-22 22:38:49.316842+03
3	auth	0001_initial	2025-12-22 22:38:49.342749+03
4	auth	0002_alter_permission_name_max_length	2025-12-22 22:38:49.346246+03
5	auth	0003_alter_user_email_max_length	2025-12-22 22:38:49.349163+03
6	auth	0004_alter_user_username_opts	2025-12-22 22:38:49.35221+03
7	auth	0005_alter_user_last_login_null	2025-12-22 22:38:49.354906+03
8	auth	0006_require_contenttypes_0002	2025-12-22 22:38:49.355852+03
9	auth	0007_alter_validators_add_error_messages	2025-12-22 22:38:49.359085+03
10	auth	0008_alter_user_username_max_length	2025-12-22 22:38:49.362635+03
11	auth	0009_alter_user_last_name_max_length	2025-12-22 22:38:49.365725+03
12	auth	0010_alter_group_name_max_length	2025-12-22 22:38:49.370899+03
13	auth	0011_update_proxy_permissions	2025-12-22 22:38:49.374491+03
14	auth	0012_alter_user_first_name_max_length	2025-12-22 22:38:49.378127+03
15	incidents	0001_initial	2025-12-22 22:38:49.488463+03
16	admin	0001_initial	2025-12-22 22:38:49.51984+03
17	admin	0002_logentry_remove_auto_add	2025-12-22 22:38:49.527359+03
18	admin	0003_logentry_add_action_flag_choices	2025-12-22 22:38:49.535987+03
19	sessions	0001_initial	2025-12-22 22:38:49.542967+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
2j1xo631vkqcty6shaua01xjj3l2ndxa	.eJxVjDEOAiEQRe9CbYgDTBgt7T0DYWCQVQPJslsZ766bbKHtf-_9lwpxXWpYh8xhyuqsQB1-N47pIW0D-R7brevU2zJPrDdF73Toa8_yvOzu30GNo35rZjAWExRjxEYokAgcAHhvSCwBnzwxWiRr2Yk7UkQULsyJAdGQen8Aw-U3Kw:1vXyrD:y3dItz1kcBMBBK4Q_xSJF-t5kuJoYRoa4qeVyDkNSE0	2026-01-06 12:39:07.528866+03
\.


--
-- Data for Name: incidents_actionlog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_actionlog (id, action_type, description, "timestamp", user_id, appeal_id) FROM stdin;
\.


--
-- Data for Name: incidents_appeal; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_appeal (id, topic, description, created_at, closed_at, applicant_id, category_id, priority_id, status_id) FROM stdin;
1	Утечка пароля	Т.к паролем владею не только я, есть шанс внедрения стороннего человека в систему.	2025-12-23 00:33:36.877511+03	\N	2	3	3	1
\.


--
-- Data for Name: incidents_assignment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_assignment (id, assigned_at, comment, appeal_id, performer_id) FROM stdin;
\.


--
-- Data for Name: incidents_backuplog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_backuplog (id, created_at, file_name, status, file_path, initiator_id) FROM stdin;
1	2025-12-24 22:53:12.850522+03	backup_2025-12-24_22-53-08.sql	Успешно (Облако)	YandexDisk:/Course_Backups/backup_2025-12-24_22-53-08.sql	1
\.


--
-- Data for Name: incidents_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_category (id, name, description) FROM stdin;
1	Доступ	Заблокировалась учетка, забыл пароль, права доступа
2	Оборудование	Сломался принтер, не включается ПК, монитор
3	Инцидент ИБ	Вирус, фишинг, подозрительная активность
4	ПО	Ошибки в Word, Excel, 1С, браузере
\.


--
-- Data for Name: incidents_comment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_comment (id, text, created_at, appeal_id, author_id) FROM stdin;
1	Принято в обработку. Попов В.А	2025-12-23 11:29:48.627398+03	1	2
2	Вот теперь принято в обработку. Попов В.А. Сергею устное предупреждение.	2025-12-23 11:39:56.568734+03	1	1
\.


--
-- Data for Name: incidents_customuser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, fio, phone, department_id, role_id) FROM stdin;
2	pbkdf2_sha256$1200000$DqTnq0eq91vrV7UnqA1cFK$xrsnD8T/Mtj4TDasu+aZdPTUyarQoNk3v6ydcewb0Js=	2025-12-23 12:14:45.301329+03	f	serega_metkyi			serega-hacker@gmail.com	f	t	2025-12-23 00:09:23.227803+03	Ткаченко Сергей Борисович	+ 7 910 472 90 15	1	6
1	pbkdf2_sha256$1200000$bQ1yXIESsKAtgvoTgXCRjw$XYWsnpKNL42CGt4cfM9zzkMqgaYEy7WOtA/qRMVAZc0=	2025-12-23 12:39:07.527333+03	t	admin				t	t	2025-12-22 22:41:23+03	Попов Владислав Александрович		\N	4
\.


--
-- Data for Name: incidents_customuser_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: incidents_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: incidents_department; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_department (id, name, description, head, phone) FROM stdin;
1	Отдел по борьбе	Test	Попов.В.А	+7 920 241 41 20
\.


--
-- Data for Name: incidents_priority; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_priority (id, level, description) FROM stdin;
1	Низкий	Не влияет на бизнес-процессы
2	Средний	Затрагивает одного пользователя
3	Высокий	Затрагивает отдел или группу
4	Критический	Блокирует работу организации
\.


--
-- Data for Name: incidents_report; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_report (id, report_type, created_at, appeal_count, file_path, initiator_id) FROM stdin;
\.


--
-- Data for Name: incidents_role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_role (id, name, description) FROM stdin;
4	Admin	Администратор системы (полные права)
5	Staff	Сотрудник службы ИБ (обработка заявок)
6	User	Обычный пользователь (создание заявок)
\.


--
-- Data for Name: incidents_status; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidents_status (id, name, description) FROM stdin;
1	Новое	Заявка только создана, еще не обработана
2	В работе	Сотрудник ИБ принял заявку в работу
3	Ожидание	Ждем ответа от пользователя или поставщика
4	Закрыто	Проблема решена, заявка закрыта
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 8, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: incidents_actionlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_actionlog_id_seq', 1, false);


--
-- Name: incidents_appeal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_appeal_id_seq', 1, true);


--
-- Name: incidents_assignment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_assignment_id_seq', 1, false);


--
-- Name: incidents_backuplog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_backuplog_id_seq', 1, true);


--
-- Name: incidents_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_category_id_seq', 4, true);


--
-- Name: incidents_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_comment_id_seq', 2, true);


--
-- Name: incidents_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_customuser_groups_id_seq', 1, false);


--
-- Name: incidents_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_customuser_id_seq', 2, true);


--
-- Name: incidents_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_customuser_user_permissions_id_seq', 1, false);


--
-- Name: incidents_department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_department_id_seq', 1, true);


--
-- Name: incidents_priority_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_priority_id_seq', 4, true);


--
-- Name: incidents_report_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_report_id_seq', 1, false);


--
-- Name: incidents_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_role_id_seq', 6, true);


--
-- Name: incidents_status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidents_status_id_seq', 4, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: incidents_actionlog incidents_actionlog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_actionlog
    ADD CONSTRAINT incidents_actionlog_pkey PRIMARY KEY (id);


--
-- Name: incidents_appeal incidents_appeal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_appeal
    ADD CONSTRAINT incidents_appeal_pkey PRIMARY KEY (id);


--
-- Name: incidents_assignment incidents_assignment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_assignment
    ADD CONSTRAINT incidents_assignment_pkey PRIMARY KEY (id);


--
-- Name: incidents_backuplog incidents_backuplog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_backuplog
    ADD CONSTRAINT incidents_backuplog_pkey PRIMARY KEY (id);


--
-- Name: incidents_category incidents_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_category
    ADD CONSTRAINT incidents_category_pkey PRIMARY KEY (id);


--
-- Name: incidents_comment incidents_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_comment
    ADD CONSTRAINT incidents_comment_pkey PRIMARY KEY (id);


--
-- Name: incidents_customuser_groups incidents_customuser_gro_customuser_id_group_id_049d0881_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser_groups
    ADD CONSTRAINT incidents_customuser_gro_customuser_id_group_id_049d0881_uniq UNIQUE (customuser_id, group_id);


--
-- Name: incidents_customuser_groups incidents_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser_groups
    ADD CONSTRAINT incidents_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: incidents_customuser incidents_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser
    ADD CONSTRAINT incidents_customuser_pkey PRIMARY KEY (id);


--
-- Name: incidents_customuser_user_permissions incidents_customuser_use_customuser_id_permission_3c0411f7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser_user_permissions
    ADD CONSTRAINT incidents_customuser_use_customuser_id_permission_3c0411f7_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: incidents_customuser_user_permissions incidents_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser_user_permissions
    ADD CONSTRAINT incidents_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: incidents_customuser incidents_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser
    ADD CONSTRAINT incidents_customuser_username_key UNIQUE (username);


--
-- Name: incidents_department incidents_department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_department
    ADD CONSTRAINT incidents_department_pkey PRIMARY KEY (id);


--
-- Name: incidents_priority incidents_priority_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_priority
    ADD CONSTRAINT incidents_priority_pkey PRIMARY KEY (id);


--
-- Name: incidents_report incidents_report_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_report
    ADD CONSTRAINT incidents_report_pkey PRIMARY KEY (id);


--
-- Name: incidents_role incidents_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_role
    ADD CONSTRAINT incidents_role_pkey PRIMARY KEY (id);


--
-- Name: incidents_status incidents_status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_status
    ADD CONSTRAINT incidents_status_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: incidents_actionlog_appeal_id_aaa030f0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_actionlog_appeal_id_aaa030f0 ON public.incidents_actionlog USING btree (appeal_id);


--
-- Name: incidents_actionlog_user_id_c7bece66; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_actionlog_user_id_c7bece66 ON public.incidents_actionlog USING btree (user_id);


--
-- Name: incidents_appeal_applicant_id_f0a63025; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_appeal_applicant_id_f0a63025 ON public.incidents_appeal USING btree (applicant_id);


--
-- Name: incidents_appeal_category_id_cd93c24c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_appeal_category_id_cd93c24c ON public.incidents_appeal USING btree (category_id);


--
-- Name: incidents_appeal_priority_id_d37ab2ed; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_appeal_priority_id_d37ab2ed ON public.incidents_appeal USING btree (priority_id);


--
-- Name: incidents_appeal_status_id_6c930655; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_appeal_status_id_6c930655 ON public.incidents_appeal USING btree (status_id);


--
-- Name: incidents_assignment_appeal_id_4516b61f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_assignment_appeal_id_4516b61f ON public.incidents_assignment USING btree (appeal_id);


--
-- Name: incidents_assignment_performer_id_98750d21; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_assignment_performer_id_98750d21 ON public.incidents_assignment USING btree (performer_id);


--
-- Name: incidents_backuplog_initiator_id_67b1e716; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_backuplog_initiator_id_67b1e716 ON public.incidents_backuplog USING btree (initiator_id);


--
-- Name: incidents_comment_appeal_id_d35e88d5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_comment_appeal_id_d35e88d5 ON public.incidents_comment USING btree (appeal_id);


--
-- Name: incidents_comment_author_id_65f63249; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_comment_author_id_65f63249 ON public.incidents_comment USING btree (author_id);


--
-- Name: incidents_customuser_department_id_efee6b4e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_customuser_department_id_efee6b4e ON public.incidents_customuser USING btree (department_id);


--
-- Name: incidents_customuser_groups_customuser_id_b988f0e3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_customuser_groups_customuser_id_b988f0e3 ON public.incidents_customuser_groups USING btree (customuser_id);


--
-- Name: incidents_customuser_groups_group_id_31b86419; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_customuser_groups_group_id_31b86419 ON public.incidents_customuser_groups USING btree (group_id);


--
-- Name: incidents_customuser_role_id_c8909c46; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_customuser_role_id_c8909c46 ON public.incidents_customuser USING btree (role_id);


--
-- Name: incidents_customuser_user_permissions_customuser_id_aa46cf0a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_customuser_user_permissions_customuser_id_aa46cf0a ON public.incidents_customuser_user_permissions USING btree (customuser_id);


--
-- Name: incidents_customuser_user_permissions_permission_id_d8cf96ed; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_customuser_user_permissions_permission_id_d8cf96ed ON public.incidents_customuser_user_permissions USING btree (permission_id);


--
-- Name: incidents_customuser_username_68866f77_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_customuser_username_68866f77_like ON public.incidents_customuser USING btree (username varchar_pattern_ops);


--
-- Name: incidents_report_initiator_id_c24e1df6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX incidents_report_initiator_id_c24e1df6 ON public.incidents_report USING btree (initiator_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_incidents_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_incidents_customuser_id FOREIGN KEY (user_id) REFERENCES public.incidents_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_actionlog incidents_actionlog_appeal_id_aaa030f0_fk_incidents_appeal_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_actionlog
    ADD CONSTRAINT incidents_actionlog_appeal_id_aaa030f0_fk_incidents_appeal_id FOREIGN KEY (appeal_id) REFERENCES public.incidents_appeal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_actionlog incidents_actionlog_user_id_c7bece66_fk_incidents_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_actionlog
    ADD CONSTRAINT incidents_actionlog_user_id_c7bece66_fk_incidents_customuser_id FOREIGN KEY (user_id) REFERENCES public.incidents_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_appeal incidents_appeal_applicant_id_f0a63025_fk_incidents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_appeal
    ADD CONSTRAINT incidents_appeal_applicant_id_f0a63025_fk_incidents FOREIGN KEY (applicant_id) REFERENCES public.incidents_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_appeal incidents_appeal_category_id_cd93c24c_fk_incidents_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_appeal
    ADD CONSTRAINT incidents_appeal_category_id_cd93c24c_fk_incidents_category_id FOREIGN KEY (category_id) REFERENCES public.incidents_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_appeal incidents_appeal_priority_id_d37ab2ed_fk_incidents_priority_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_appeal
    ADD CONSTRAINT incidents_appeal_priority_id_d37ab2ed_fk_incidents_priority_id FOREIGN KEY (priority_id) REFERENCES public.incidents_priority(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_appeal incidents_appeal_status_id_6c930655_fk_incidents_status_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_appeal
    ADD CONSTRAINT incidents_appeal_status_id_6c930655_fk_incidents_status_id FOREIGN KEY (status_id) REFERENCES public.incidents_status(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_assignment incidents_assignment_appeal_id_4516b61f_fk_incidents_appeal_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_assignment
    ADD CONSTRAINT incidents_assignment_appeal_id_4516b61f_fk_incidents_appeal_id FOREIGN KEY (appeal_id) REFERENCES public.incidents_appeal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_assignment incidents_assignment_performer_id_98750d21_fk_incidents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_assignment
    ADD CONSTRAINT incidents_assignment_performer_id_98750d21_fk_incidents FOREIGN KEY (performer_id) REFERENCES public.incidents_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_backuplog incidents_backuplog_initiator_id_67b1e716_fk_incidents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_backuplog
    ADD CONSTRAINT incidents_backuplog_initiator_id_67b1e716_fk_incidents FOREIGN KEY (initiator_id) REFERENCES public.incidents_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_comment incidents_comment_appeal_id_d35e88d5_fk_incidents_appeal_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_comment
    ADD CONSTRAINT incidents_comment_appeal_id_d35e88d5_fk_incidents_appeal_id FOREIGN KEY (appeal_id) REFERENCES public.incidents_appeal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_comment incidents_comment_author_id_65f63249_fk_incidents_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_comment
    ADD CONSTRAINT incidents_comment_author_id_65f63249_fk_incidents_customuser_id FOREIGN KEY (author_id) REFERENCES public.incidents_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_customuser_user_permissions incidents_customuser_customuser_id_aa46cf0a_fk_incidents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser_user_permissions
    ADD CONSTRAINT incidents_customuser_customuser_id_aa46cf0a_fk_incidents FOREIGN KEY (customuser_id) REFERENCES public.incidents_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_customuser_groups incidents_customuser_customuser_id_b988f0e3_fk_incidents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser_groups
    ADD CONSTRAINT incidents_customuser_customuser_id_b988f0e3_fk_incidents FOREIGN KEY (customuser_id) REFERENCES public.incidents_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_customuser incidents_customuser_department_id_efee6b4e_fk_incidents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser
    ADD CONSTRAINT incidents_customuser_department_id_efee6b4e_fk_incidents FOREIGN KEY (department_id) REFERENCES public.incidents_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_customuser_groups incidents_customuser_groups_group_id_31b86419_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser_groups
    ADD CONSTRAINT incidents_customuser_groups_group_id_31b86419_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_customuser_user_permissions incidents_customuser_permission_id_d8cf96ed_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser_user_permissions
    ADD CONSTRAINT incidents_customuser_permission_id_d8cf96ed_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_customuser incidents_customuser_role_id_c8909c46_fk_incidents_role_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_customuser
    ADD CONSTRAINT incidents_customuser_role_id_c8909c46_fk_incidents_role_id FOREIGN KEY (role_id) REFERENCES public.incidents_role(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incidents_report incidents_report_initiator_id_c24e1df6_fk_incidents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidents_report
    ADD CONSTRAINT incidents_report_initiator_id_c24e1df6_fk_incidents FOREIGN KEY (initiator_id) REFERENCES public.incidents_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 2iOOftOcdRDsRitUcd8oQ06Gnxz4RvtcN4JaBsDfbNVMORhEx575ConxR7kiwfa

